mcmtmod <- readRDS("female_beginMCMT.rds")
matmod <- readRDS("female_beginMAT.rds")
bffpmod <- readRDS("female_beginbFFP.rds")
latmod <- readRDS("female_beginLatitude.rds")
base <- readRDS("female_begin.rds")
latprovmod <- readRDS("female_beginLatitudeProv.rds")
emtmod <- readRDS("female_beginEMT.rds")
bigmod <-readRDS("female_beginbig.rds")
genmod <- readRDS("female_beginGen.rds")
genmodnoprov <- readRDS("female_beginGennoprov.rds")
monodepprov <- readRDS("female_beginMonodepprov.rds")
monobig <- readRDS("female_beginbigGen.rds")
monobig_noprov <- readRDS("female_beginbigGennp.rds")

summary(bffpmod)
summary(matmod)
summary(mcmtmod)
summary(latmod)
summary(base)
summary(latprovmod)
summary(emtmod)
summary(bigmod)
summary(genmod)
summary(genmodnoprov)
summary(monodepprov)
summary(monobig)
summary(monobig_noprov)

plot(conditional_effects(mcmtmod))
plot(conditional_effects(bffpmod))
plot(conditional_effects(matmod))
plot(conditional_effects(latmod))
plot(conditional_effects(emtmod))
plot(conditional_effects(monodepprov))

plot(conditional_effects(latprovmod), conditions = plotConditions)
plot(conditional_effects(genmodnoprov))
plot(conditional_effects(monobig))
plot(conditional_effects(monobig_noprov))

loomat <- readRDS("model_dev/loo_mat.rds")
loobffp <- readRDS("model_dev/loo_bffp.rds")
loomcmt <- readRDS("model_dev/loo_mcmt.rds")
loobase <- readRDS("model_dev/loo_base.rds")
loolat <- readRDS("model_dev/loo_lat.rds")
loolatprov <- readRDS("model_dev/loo_latprov.rds")
looemt <- readRDS("model_dev/loo_emt.rds")
loobig <- readRDS("model_dev/loo_big.rds")
loogennoprov <- readRDS("model_dev/loo_latgennoprov.rds")
loogen <- readRDS("model_dev/loo_latgen.rds")
loomonodep <- readRDS("model_dev/loo_latMonodepprov.rds")
loobiggen <- readRDS("model_dev/loo_latbiggen.rds")
loobiggennp <- readRDS("model_dev/loo_latbiggennp.rds")
loo_compare(loobase, loomat, loobffp, loomcmt, loolat, loolatprov, looemt, loobig, loogennoprov, loogen, loomonodep, loobiggen, loobiggennp)

loobiggen

